### ISSUE TITLE
A Data set problem

### ISSUE THREAD

**Issue by sykxiaoqiang** [LahiruJayasinghe/DeepDOA#1]
hello,I downloaded your code and there was a dataset error during training. Can you help me? Thank you very much.
![image](https://user-images.githubusercontent.com/39980148/44720122-52a5a980-aaf8-11e8-92f8-aa39be99eabf.png)

**Comment by sykxiaoqiang** [comment]
![tim 20180828192839](https://user-images.githubusercontent.com/39980148/44720183-94ceeb00-aaf8-11e8-9d33-506e7027e0e8.png)

**Comment by sykxiaoqiang** [comment]
Traceback (most recent call last):
  File "C:/Users/sykxiaoqiang/Desktop/DeepDOA-master/DNN_Ground_data_8sectors.py", line 7, in <module>
    antenna_data,label_data = data.get_synthatic_data(test_data=False)
  File "C:\Users\sykxiaoqiang\Desktop\DeepDOA-master\get_csv_data.py", line 44, in get_synthatic_data
    x_0 = genfromtxt('./Dround_Data_New/Nomalized/deg_0_normalize.csv', delimiter=',', dtype=np.float32)
  File "C:\Users\sykxiaoqiang\Anaconda3\envs\tensorflow\lib\site-packages\numpy\lib\npyio.py", line 1689, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "C:\Users\sykxiaoqiang\Anaconda3\envs\tensorflow\lib\site-packages\numpy\lib\_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "C:\Users\sykxiaoqiang\Anaconda3\envs\tensorflow\lib\site-packages\numpy\lib\_datasource.py", line 616, in open
    raise IOError("%s not found." % path)
OSError: ./Dround_Data_New/Nomalized/deg_0_normalize.csv not found.

**Comment by sykxiaoqiang** [comment]
how to use TrainDOA_Data.csv  TestDOA_Noise_Data.csv  TestDOA_Data.csv?

**Comment by LahiruJayasinghe** [comment]
@sykxiaoqiang 
There was some missing file in the repo, but this bug is fixed with new commits. Thanks for pointing out. TrainDOA_Data.csv file is the output of the denoising autoencoder. However, now these data are created on runtime and code is changed accordingly. Have a look at the comments of the main.py
Thanks

**Comment by sykxiaoqiang** [comment]
@LahiruJayasinghe  thanks for your work,i will try again!

**Comment by sykxiaoqiang** [comment]
@LahiruJayasinghe  hello,Please tell me which script is the training script？
thanks a lot

**Comment by sykxiaoqiang** [comment]
@LahiruJayasinghe i have already solved this training problem! it can be changed in main.py,right?

**Comment by LahiruJayasinghe** [comment]
@sykxiaoqiang yes, you can change it in main.py

**Comment by sykxiaoqiang** [comment]
@LahiruJayasinghe hello,can u tell me the respective function of this diffierent script like DNN_Ground_data_8sectors.py ，DenoisingAE.py and  main.py

**Comment by sykxiaoqiang** [comment]
@LahiruJayasinghe hello,is this script "get_csv_data.py" preprocessing Data-set?

**Comment by LahiruJayasinghe** [comment]
@sykxiaoqiang it is a class made for batch generation and training, testing data generation

**Comment by sykxiaoqiang** [comment]
@LahiruJayasinghe hello,i an very sorry to bother you, I would like to ask if I can provide more similar training data sets? thanks a lot for your work!

**Comment by LahiruJayasinghe** [comment]
@sykxiaoqiang Yes, it would be great

**Comment by sykxiaoqiang** [comment]
@LahiruJayasinghe Sorry, I mistyped U as I. I want to say if you can provide more relevant data sets？

**Comment by LahiruJayasinghe** [comment]
@sykxiaoqiang ohh sorry to disappoint you, this project was over. Therefore, we have only got this data set only

**Comment by sykxiaoqiang** [comment]
@LahiruJayasinghe thanks,if i get more data sets, I will provide them here.

**Comment by LahiruJayasinghe** [comment]
@sykxiaoqiang thanks and good luck (Y)
